version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      # This volume persists the data.json file
      - ./packages/server/src/data.json:/app/packages/server/dist/data.json:rw
    # Update healthcheck to use the server port
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server